// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBk2r_JeM4ILJQtH5qAaGBGYlgz0V9gk8',
    appId: '1:30753103353:web:df7a3972a50c00866cf128',
    messagingSenderId: '30753103353',
    projectId: 'crud--flutter',
    authDomain: 'crud--flutter.firebaseapp.com',
    storageBucket: 'crud--flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaQ_HhKe77R9TKcciuHDd8xSrxbfjGo1k',
    appId: '1:30753103353:android:46d87e56a2f2c7f06cf128',
    messagingSenderId: '30753103353',
    projectId: 'crud--flutter',
    storageBucket: 'crud--flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3JGpHnVt7zW-wGpud6MwHwsVBH-KByZw',
    appId: '1:30753103353:ios:43c850fb0832dd706cf128',
    messagingSenderId: '30753103353',
    projectId: 'crud--flutter',
    storageBucket: 'crud--flutter.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3JGpHnVt7zW-wGpud6MwHwsVBH-KByZw',
    appId: '1:30753103353:ios:43c850fb0832dd706cf128',
    messagingSenderId: '30753103353',
    projectId: 'crud--flutter',
    storageBucket: 'crud--flutter.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBk2r_JeM4ILJQtH5qAaGBGYlgz0V9gk8',
    appId: '1:30753103353:web:d5f983f24e42d22b6cf128',
    messagingSenderId: '30753103353',
    projectId: 'crud--flutter',
    authDomain: 'crud--flutter.firebaseapp.com',
    storageBucket: 'crud--flutter.appspot.com',
  );
}
